- name: Update apt cache
  action: apt update_cache=yes

- name: Install dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - git
    - curl
    - libcurl4-openssl-dev
    - build-essential
    - nodejs
    - python
    - python-pycurl
    - python-psycopg2
    - python-software-properties
    - libpq-dev
