- name: Update Nginx configuration
  template: src=nginx.conf.j2
            dest=/usr/local/nginx/conf/nginx.conf

- name: Check Nginx configuration
  shell: /usr/local/nginx/sbin/nginx -t
  notify:
    - reload nginx

- name: Deny access to port 4000
  ufw: rule=deny port=4000

- name: Allow access to port 22
  ufw: rule=allow port=22

- name: Allow access to port 80
  ufw: rule=allow port=80

- name: Allow access to port 443
  ufw: rule=allow port=443

- name: Allow access to port 1935
  ufw: rule=allow port=1935

- name: Allow access to port 8080
  ufw: rule=allow port=8080

- name: Enable firewall
  ufw: state=enabled
